apiVersion: v1
kind: Config
clusters:
  - name: kubernetes
    cluster:
      certificate-authority: /secret/trust.pem
      server: #https://${MASTER}:6443
users:
  - name: kubelet
    user:
      client-certificate: /secret/host.cer
      client-key: /secret/host.key
contexts:
  - name: default-context
    context:
      cluster: kubernetes
      user: kubelet
current-context: default-context
